language: node_js
node_js:
  - 10.15.1
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test

deploy:
  provider: surge
  project: ./build/
  domain: raining-emojis.surge.sh
  on:
    tags: true
  skip_cleanup: true
